### ISSUE TITLE
Añadir pagina 'Detalle Camiseta'

### ISSUE THREAD

**Issue by AsecPineda** [CarlosPuyana/CatalogoCamisetas#2]

**Comment by CarlosPuyana** [comment]
No está funcionando correctamente, da un no existe constantemente. Me pongo con ello

**Comment by CarlosPuyana** [comment]
Arreglado, estaba pasando que al hacer inicialmente la busqueda de camisetas por la nueva temporada, las de otras temporadas no la encontraba porque no estaban inicializado en el modelo de datos
